global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    project: 'grafana-monitoring'

# Định nghĩa file chứa alert rules
rule_files:
  - "alerts.yml"

# Cấu hình scrape metrics
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
    metrics_path: /metrics
    scrape_interval: 15s

# Cấu hình Alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']